### PR TITLE
Full 1.8.8 port and merged changes from 1.1.1.1

### PR DESCRIPTION
**Pull request by gigabit101**
…ory and getCommandSenderName() seem N/A in this use

### CODE REVIEW

**Comment by GirafiStudios** [comment]
Wouldn't it be an idea to update the build.gradle and similiar too ? ;)

**Comment by gigabit101** [comment]
It compiles with new build script and works perfectly

**Comment by GirafiStudios** [comment]
(y)

**Comment by Azanor** [comment]
Thanks for this, but a few recent changes to mcp mappings and forge means now that I am ready to merge it, it also is a bit out of date - I should have merged it earlier. Its cool, I will just quickly do the update myself.

**Pull request closed without merging**
