### PR TITLE
Ported to 1.9.4

### PR DESCRIPTION
**Pull request by GirafiStudios**
Very easy update, only version and mappings changes. Figured I would just make a PR, to help out a bit :)

### CODE REVIEW

**Comment by williewillus** [comment]
are you sure?
Some of the baubles code needs to be changed due to the new mappings

**Comment by williewillus** [comment]
for example CreativeTabs in ItemRing

**Comment by GirafiStudios** [comment]
The mappings was updated in https://github.com/Azanor/Baubles/pull/131 , so Baubles was already pretty much on latest mappings version. I just updated to what Forge uses for 1.9.4.

**Comment by williewillus** [comment]
Ah I see

**Comment by Azanor** [comment]
Thanks :)

**Pull request merged**
