### PR TITLE
IBauble capability for 1.12

### PR DESCRIPTION
**Pull request by Xalcon**
port of https://github.com/Azanor/Baubles/pull/208 to 1.12 :)
Tested with my PotionBauble testmod https://gist.github.com/Xalcon/9a6473329b50965674b4c59f7886ec07

example

### CODE REVIEW

**Comment by Xalcon** [comment]
If you know any mod that already uses baubles in 1.12, hit me up, so I can test it :)

**Comment by Azanor** [comment]
I'm currently working on SlotBauble.java in 1.11 to fix some issues in regards to the onUnequip event. Will do a commit there once I sort it out.

**Comment by Xalcon** [comment]
ok, i'll wait until you did your stuff in the 1.11 and 1.12 branches and then I update the PR :) no hurry

**Comment by Azanor** [comment]
1.11 branch has been updated

**Comment by Xalcon** [comment]
do you want me to include the bugfix as well? I mind doing that, but ill will take around 2h before I can get to it.

**Comment by Azanor** [comment]
There is no hurry, so if you can do it, it would be great. Otherwise I will try and get to it tomorrow.

**Comment by Xalcon** [comment]
@Azanor i added the fixes from your commit exluding the version updates. Hope this is ok :)
Quickly tested it with the ring and my potions and the sounds work on shift click (onUnequip())

**Comment by Xalcon** [comment]
its already merged for 1.11 :) give azanor some time and we will get it for 1.12 as well

**Comment by Thutmose** [comment]
Ya, as I already have it working in one direction:
image

So as soon as that is done, I can also get the other way :D

**Comment by Thutmose** [comment]
image

Got it working both ways on my 1.11.2 branch :D

**Comment by PrinceOfAmber** [comment]
Re @Xalcon  , Cyclic has a bunch of Baubles compatible items

**Comment by Azanor** [comment]
Thanks for this :)

**Comment by AbrahamtheFenix2003** [comment]
> Sí, como ya lo tengo funcionando en una dirección: imagen
> 
> Tan pronto como esté hecho, también puedo hacerlo al revés :D

tienen una version diferente para baubles 1.12.2?

**Pull request merged**
