### PR TITLE
Changed bauble save files from using player names to ID & Server crash fix

### LINKED ISSUE #89: Username change
When you change your username with the new mojang feature from today all items in the bauble slots are gone.
Reason: The items are save in <username>.baub and you need to you the uuid.

### LINKED ISSUE #90: Compatibility issue with Sync due to baubles being... global?
Not sure if global is the correct term to use for this. I believe tinkerer's construct also still exhibits this issue with their knapsack and additional 'armor slots'. My goal is to use the "Sync" mod in conjunction with mods that utilize the Baubles mod. I'm also trying to use OpenBlocks as well, but that should be.. mostly unrelated. The sync mod creates clones of the player that have separate inventories. When I change from my original body to clone 1 my original body's inventory, hotbar, and armor remain on my original character. If I'm playing on a clone and I die, I return to the body of another clone or to my original body. 

The problem is that baubles exist across the original body and all clones, they do not stay with the body they were equip on. The additional resulting problem is that if I die on a clone the bauble will no longer be equipped on the intended body, for it dropped upon death.

I made a fresh instance using MultiMC to confirm the behavior. It was running Minecraft 1.7.10 with Forge 10.13.2.1307. Mods installed were Baubles 1.7.10-1.0.1.10, iChunUtil-4.1.3, Sync-4.0.0, OpenBlocks-1.7.10-1.3-snapshot-556, OpenModsLib-1.7.10.0.6-snapshot-307. I said 'mostly unrelated' in regards to OpenBlocks before because I didn't test if the Baubles are dropped to the floor-- I tested if they are dropped into the OpenBlocks grave that is left behind on death (which they are.)

My fml-client-latest.log file is apparently slightly too big to upload to pastebin, so if you think it's necessary please recommend somewhere for me to upload it ; ;.

### PR DESCRIPTION
**Pull request by Jamerboy**
Changed the way baubles are saved by binding a bauble inventory file to a player's save file, This fixes #90, fixes #89, while hopefully working around the Thaumcraft bug Azanor mentioned. Also fixed issues #92 and #86  by moving the rendering into the client proxy instead of calling it in init

### CODE REVIEW

**Comment by Azanor** [comment]
Does this fix take the offline UUID into account?

**Comment by Jamerboy** [comment]
Nope, it was basically giving every player a specific baubles inventory id using extended properties. The save file names might look a bit weird, but since all player saves are using UUID, I don't think this would be more confusing than it already is.

**Comment by copygirl** [comment]
Still wondering why not completely move over to IExtendedEntityProperties. This workaround / fix seems odd. Would it create multiple baubles files for a single player, especially in case of Sync, since this is supposed to fix that? If that's the case, I doubt they could be properly removed / cleaned up.

**Comment by Jamerboy** [comment]
@copygirl Yeah, maybe. I just did this due to the Thaumcraft bug that Azanor mentioned.  If it's not much of an issue. Probably I should close this.

**Comment by Azanor** [comment]
Yeah, storing the data as part of the normal player save files is a much simpler solution. I want to play with it a bit however.

**Pull request closed without merging**
