### PR TITLE
Feature/bauble capability

### PR DESCRIPTION
**Pull request by Xalcon**
Hi Azanor, 
This feature was requested by @darkhax in #183  a while ago.

This PR replaces the whole IBauble item logic with a capability variant. I've added some backwards compatibility code that allows using IBauble as an interface for an Item as well as a capability.

* Registered IBauble as a capability `CAPABILITY_ITEM_BAUBLE`
* Replaced all `(IBauble)itemStack.getItem()` calls with `itemStack.getCapability()`
* Added compatibility event handler that adds the IBauble capability to all items, that implement the IBauble interface

> Note: I did see a lot of null checks for Itemstacks. These checks are always false, due to the Itemstack changes in 1.11.2. I did not refactor that code to reduce the amount of changes done by this PR.

This code has been successfuly tested with Botania 1.11.2-r1.9-343. I've also tested some custom capability that adds IBauble to the minecraft potions, [an example can be found here](https://gist.github.com/Xalcon/9a6473329b50965674b4c59f7886ec07).

I did  not do any ports to 1.10.2 or below yet since I'd like to get some feedback on this code first :)

### CODE REVIEW

**Comment by gr8pefish** [comment]
I'd like to see this PR accepted. Azanor, any thoughts?

**Comment by Azanor** [comment]
I'll check it out once I get a bit of time this week.

**Comment by Azanor** [comment]
I've merged this with the 1.11 branch for now. Mostly my own fault for taking so long - I wouldn't have been able to easily merge it into the new master which is for MC 1.12

**Comment by Xalcon** [comment]
All good :) I'll make a PR for the 1.12 branch as well.

**Pull request merged**
